# -*- coding: utf-8 -*-
"""ЛискаВМ_ЛБ2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nVifxkAPFObGNE7DHSmxTSF2T36FJKXs

Лиска Вадим Максимовчи ФІТ 4-5 Л_Б_2 Варіант_11
"""

#Імпортуємо необхідні для проекту бібліотеки.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#Додаємо посилання на таблицю.
url = "https://uk.wikipedia.org/wiki/%D0%A1%D0%B5%D1%80%D0%B5%D0%B4%D0%BD%D1%8F_%D0%B7%D0%B0%D1%80%D0%BE%D0%B1%D1%96%D1%82%D0%BD%D0%B0_%D0%BF%D0%BB%D0%B0%D1%82%D0%B0_%D0%B2_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%96"
#Зчитуємо таблицю.
data = pd.read_html(url, header=0)[2]
#Задаємо необхідну кількість рядків таблиці, яку потрібно вивести.
df_1 = data.head(5)
#Виводимо перші 5 рядків таблиці.
print(df_1)

#Визначаємо кількість рядків та стовпчиків ( через атрибут shape ).
num_rows, num_columns = data.shape
print(f"Кількість рядків: {num_rows}")
print(f"Кількість стовпчиків: {num_columns}")

#Визначаємо загальну кількість років та місяців з даних таблиці.
num_years = len(data['Рік']) - 1
num_months = num_years*12
print("Загальна кількість років:", num_years)
print("Загальна кількість місяців:", num_months)

#Замінюємо пропущені значення "—" в таблиці на "NaN"
data = data.rename(columns={
    "Рік": "Year",
    "В національнійвалюті": "Salary in UAH",
    "В доларах США": "Salary in USD",
    "Кількість кгхліба[20] на середнюзарплату": "Bread per Salary",
    "Кількість БігМаківна середню зарплату": "BigMacs per Salary"
})
data = data.replace("—", np.nan)
data

#Визначаємо тип стовпців за допомогою dtypes.
column_types = data.dtypes
print("Типи стовпців:")
print(column_types)

#Видаляємо два останніх стовпця із таблиці.
#Назву стовпця вказати із виведенної таблиці завдання №4.
data = data.drop(columns=["Кількість кг хліба[20] на середню зарплату", "Кількість БігМаків на середню зарплату"])
data

#Видаляємо знаки "*" у останніх двох роках.
data["Year"] = data["Year"].str.replace("*", "")
data["Year"] = data["Year"].astype(int)
data

#Видаляємо стрілочки із таблиці. ("▲" та "▼").
data["В національній валюті"] = data["В національній валюті"].str.replace('▲', "").str.replace('▼', "")
data["Salary in USD"] = data["Salary in USD"].str.replace('▲', "").str.replace('▼', "")
data

#Визначаємо тип стовпців.
data.dtypes

#Змінюємо тип даних з нечислових на числові.
data['В національній валюті'] = data['В національній валюті'].str.replace(',', '.').astype(float)
data['Salary in USD'] = data['Salary in USD'].str.replace(',', '.').astype(float)
data

#Перевіряємо чи змінився тип даних.
data.dtypes

data

#Рахуємо частку пропусків в кожній колонці.
missing_data = data.isna().sum()/len(data)*100
print("Кількість пропусків у кожному стовпці:")
print(missing_data)

#Вираховуємо найбільшу заробітну плату в Україні.
max_in_national_currency = data['В національній валюті'].max()
max_in_usd = data['Salary in USD'].max()

#Знаходимо рік, коли у різних валютах була найбільша заробітна плата.
year_max_in_national_currency = data.loc[data['В національній валюті'] == max_in_national_currency, 'Year'].values[0]
year_max_in_usd = data.loc[data['Salary in USD'] == max_in_usd, 'Year'].values[0]
print(f"Максимальна заробітна плата в національній валюті: {max_in_national_currency}грн. була в {year_max_in_national_currency} році.")
print(f"Максимальна заробітна плата в USD: {max_in_usd}$ була в {year_max_in_usd} році.")

#Знаходимо рік з мінімальною  зарплатою в Україні в національній валюті та в  доларах США.
min_in_national_currency = data['В національній валюті'].min()
min_in_usd = data['Salary in USD'].min()

#Знаходимо рік, коли у різних валютах була найменша заробітна плата.
year_min_in_national_currency = data.loc[data['В національній валюті'] == min_in_national_currency, 'Year'].values[0]
year_min_in_usd = data.loc[data['Salary in USD'] == min_in_usd, 'Year'].values[0]
print(f"Мінімальна заробітна плата в національній валюті: {min_in_national_currency}грн. була в {year_min_in_national_currency} році.")
print(f"Мінімальна заробітна плата в USD: {min_in_usd}$ була в {year_min_in_usd} році.")

#Обчислюємо заробітну плату вище середньої в Україні.
average_value = data['В національній валюті'].mean()
above_average_years = data[data['В національній валюті'] > average_value]
for index, row in above_average_years.iterrows():
    year = row['Year']
    value = row['В національній валюті']
    print(f"Заробітна плата, яка перевищує середню заробітню плату в Україні була в {year:.0f} році: {value}грн.")

data
df = pd.DataFrame(data)
years = df['Salary in USD']
values = df['Year']

# Створюємо графік.
plt.figure(figsize=(10, 6))
plt.plot(values, years, marker='o', linestyle='-', color='r')
plt.title('Зміна заробітної плати з часом в USD')
plt.xlabel('Рік')
plt.ylabel('USD')
plt.grid(True)

# Відображаємо графік.
plt.show()

#Графік, що відображає середню зарплату в Україні в розрізі років без останнього року.
data
# Створюємо графік.
df = pd.DataFrame(data)
average_salary_by_year = df.groupby('Year')['Salary in USD'].mean()
plt.figure(figsize=(10, 6))
plt.plot(average_salary_by_year.index, average_salary_by_year.values, marker='o', linestyle='-', color='g')
plt.title('Середня зарплата за роками')
plt.xlabel('Рік')
plt.ylabel('Середня зарплата в USD')
plt.grid(True)

# Виведення графіку.
plt.show()

data
df = pd.DataFrame(data)

last_two_years = df[df['Year'] >= 2022]
average_salary_last_two_years = last_two_years['Salary in USD'].mean()
last_five_years = df[df['Year'] >= 2019]
average_salary_last_five_years = last_five_years['Salary in USD'].mean()

if average_salary_last_two_years > average_salary_last_five_years:
    result = "зарплата за останні два роки вища за зарплату за останні 5 років"
elif average_salary_last_two_years < average_salary_last_five_years:
    result = "зарплата за останні два роки нижча за зарплату за останні 5 років"
else:
    result = "зарплата за останні два роки дорівнює зарплаті за останні 5 років"

# Виводимо результат порівняння
print(f"Середня зарплата за останні два роки: {average_salary_last_two_years:.2f} USD")
print(f"Середня зарплата за останні 5 років: {average_salary_last_five_years:.2f} USD")
print(f"Результат порівняння: {result}")

#Порівнюємо заробітну плату в Україні за 2022 та 2023 роки ( останні доступні роки в таблиці ).
data = data[data['Year'].isin([2022, 2023])]
national_currency_values = data['В національній валюті'].values
print(f"Заробітна плата в національній валюті за 2022 рік: {national_currency_values[0]}грн.")
print(f"Заробітна плата в національній валюті за 2023 рік: {national_currency_values[1]}грн.")

if national_currency_values[0] > national_currency_values[1]:
    print(f"Заробітна плата в національній валюті за 2022 рік більше за заробітну плату за 2023 рік.")
    difference = round(national_currency_values[0] - national_currency_values[1], 2)
    print(f"Різниця: {difference:.2f}грн.")
elif national_currency_values[0] < national_currency_values[1]:
    print(f"Заробітна плата в національній валюті за 2022 рік менше за заробітну плату за 2023 рік.")
    difference = round(national_currency_values[1] - national_currency_values[0], 2)
    print(f"Різниця: {difference:.2f}грн.")